### Create Array
NumPy provides the foundation data structures and operations for SciPy

In [2]:
import numpy
mylist = [1, 2, 3]
myarray = numpy.array(mylist)
print(myarray)
print(myarray.shape)

[1 2 3]
(3,)


### Access Data

In [5]:
# access values
import numpy
mylist = [[1, 2, 3], [3, 4, 5]]
myarray = numpy.array(mylist)
print(myarray)
print(myarray.shape)
print("First row: %s",myarray[0])
print("Last row: %s",myarray[-1])
print("Specific row and col: %s",myarray[0, 2])
print("Whole col: %s",myarray[:, 2])

[[1 2 3]
 [3 4 5]]
(2, 3)
First row: %s [1 2 3]
Last row: %s [3 4 5]
Specific row and col: %s 3
Whole col: %s [3 5]


In [7]:
# arithmetic
import numpy
myarray1 = numpy.array([2, 2, 2])
myarray2 = numpy.array([3, 3, 3])
print("Addition: %s",(myarray1 + myarray2))
print("Multiplication: %s",(myarray1 * myarray2))

Addition: %s [5 5 5]
Multiplication: %s [6 6 6]
